apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ian.ward@softwareag.com
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - selector:
        dnsZones:
          - "ig.eks-iw.au-poc.com"
      dns01:
        route53:
          region: ap-southeast-2
          accessKeyID: AKIA36ZRBUR7O3Q7E6HK
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
