apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  labels:
    app: elasticsearch-deployment
spec:
  # storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
