kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: fleetman-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - fleetman-development.aks.au-poc.com
      secretName: fleetman-development-tls-secret
  rules:
    - host: fleetman-development.aks.au-poc.com
      http:
        paths:
          - path: /
            backend:
              serviceName: fleetman-webapp
              servicePort: 80