apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  labels:
    app: staff-service
    version: v6
spec:
  selector:
    matchLabels:
      app: staff-service
      version: v6
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: staff-service
        version: v6
    spec:
      containers:
      - name: staff-service
        image: ianmward/istio-fleetman-staff-service:6
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080